# If a floodgate UUID is found, use this link
# Avaliable placeholders, {XUID} {UUID} {USERNAME}

# Default: https://mc-heads.net/skin/{UUID}
floodgate-url: "https://mc-heads.net/skin/{UUID}"

# If it's not a floodgate UUID, use this api
# Avaliable placeholders, {UUID} {USERNAME}

# Default: https://minotar.net/skin/{UUID}
normal-url: "https://minotar.net/skin/{UUID}"

# Log everything, recommended when unknown errors are found

# Default: false

verbose-logging: false