name: AdvancedBlueMapSkins
version: ${project.version}
main: xyz.semetrix.advancedbluemapskins.Main
api-version: 1.17
depend:
  - BlueMap
  - floodgate
author: TechnicJelle, Semetrix
description: ${project.description}
website: ${project.url}
